### ISSUE TITLE
fabmodules won't communicate with MDX-20

### ISSUE THREAD

**Issue by rahji** [FabModules/fabmodules-html5#16] opened 2016-01-12 21:00 UTC
I have installed mod_server and it is running. The URL is correct in the fabmodules.org form. MDX20 has the safety cover down and is not in View mode. All works fine in old fab modules as it has for years. Fabmodules.org doesn't seem to communicate with the machine and generates no errors that I can see. Screen capture here: https://www.youtube.com/watch?v=szpnw9DNqpA

**Comment by fibasile** [comment] 2016-03-03 08:40
Please read the docs on the wiki, closing the issue as this is not a bug.

**Closed as completed by fibasile** 2016-03-03 08:40 UTC
